easy_admin:
   site_name: WearCoolStuff  / Administration
   
   entities:
       # List the entity class name you want to manage
       - App\Entity\Article
       - App\Entity\Commande
       - App\Entity\DetailCommande
       - App\Entity\User
    