easy_admin:
    site_name: WearCoolStuff  / Administration
<<<<<<< HEAD

    design:
        menu:
            - { route: "homepage", label: "Retourner sur le site", icon: "home" }
            - { entity: "Article", label: "Articles"}
            - { entity: "Commande", label: "Commandes" }
            - { entity: "DetailCommande", label: "Détail des Commandes" }
            - { entity: "User", label: "Gérer les utilisateurs" }

    entities:
        Article:
            class: App\Entity\Article

        Commande:
            class: App\Entity\Commande

        DetailCommande:
            class: App\Entity\DetailCommande
       
        User:
            class: App\Entity\User
  
=======
   
    design:
        menu:
        - { route: "homepage", label: "Retour à l'accueil du site", icon: "home" }
        - { entity: "Article", label: "Articles", icon: "bookmark" }
        - { entity: "Commande", label: "Commandes", icon: "check" }
        - { entity: "DetailCommande", label: "Détails des commandes", icon: "list-alt" }
        - { entity: "User", label: "Gestion des utilisateurs", icon: "user" }

    entities:
        # List the entity class name you want to manage
        - App\Entity\Article
        - App\Entity\Commande
        - App\Entity\DetailCommande
        - App\Entity\User
    
>>>>>>> master
